export const tutorialTracks = [
  {
    key: 0,
    id: 0,
    text: "Hello and welcome to WordPlay!",
    octave: 2,
    speed: 1,
    root: "",
    instrument: "Synth",
    volume: 0,
    isMuted: false,
  },
  {
    key: 1,
    id: 1,
    text: "If we use some characters like this... We can insert pauses",
    octave: 3,
    speed: 0.5,
    root: "",
    instrument: "AM",
    volume: 0,
    isMuted: false,
  },
  {
    key: 2,
    id: 2,
    text: "If we SCREAM or use exclamation OUR WORDS HIT HARDER!",
    octave: 4,
    speed: 1,
    root: "",
    instrument: "Duo",
    volume: -21,
    isMuted: false,
  },
  {
    key: 3,
    id: 3,
    text: "We can also change the speed; octave; and root note in the right panel",
    octave: 4,
    speed: 0.5,
    root: "Gb",
    instrument: "Mono",
    volume: -14,
    isMuted: false,
  },
  {
    key: 4,
    id: 4,
    text: "The loooooonger the word the looonger the note!",
    octave: 2,
    speed: 1,
    root: "",
    instrument: "Metal",
    volume: -31,
    isMuted: false,
  },
  {
    key: 5,
    id: 5,
    text: "Need help? Check the help... menu in the navbar",
    octave: 1,
    speed: 0.5,
    root: "",
    instrument: "Membrane",
    volume: 0,
    isMuted: false,
  },
];
